#ifndef ENUMS_H
#define ENUMS_H TRUE

enum 
{ 
	IDCMP_SIZEVERIFY, IDCMP_NEWSIZE, IDCMP_REFRESHWINDOW,
	IDCMP_MOUSEBUTTONS, IDCMP_MOUSEMOVE, IDCMP_GADGETDOWN,
	IDCMP_GADGETUP, IDCMP_REQSET, IDCMP_MENUPICK, 
	IDCMP_CLOSEWINDOW, IDCMP_RAWKEY, IDCMP_REQVERIFY,
	IDCMP_REQCLEAR, IDCMP_MENUVERIFY, IDCMP_NEWPREFS,
	IDCMP_DISKINSERTED, IDCMP_DISKREMOVED, IDCMP_WBENCHMESSAGE,
	IDCMP_ACTIVEWINDOW, IDCMP_INACTIVEWINDOW, IDCMP_DELTAMOVE,
	IDCMP_VANILLAKEY, IDCMP_INTUITICKS, IDCMP_IDCMPUPDATE,
	IDCMP_MENUHELP, IDCMP_CHANGEWINDOW, IDCMP_GADGETHELP	
};

#endif
